CREATE TABLE [dbo].[CLIENT] (
    [NCLI]     CHAR (4)      NOT NULL,
    [NOM]      NVARCHAR (50) NOT NULL,
    [LOCALITE] NVARCHAR (50) NOT NULL,
    [CAT]      NVARCHAR (2)  NULL,
    [COMPTE]   INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([NCLI] ASC)
);
CREATE TABLE [dbo].[COMMANDE] (
    [NCOM]    CHAR (4) NOT NULL,
    [NCLI]    CHAR (4) NOT NULL,
    [DATECOM] DATE     NOT NULL,
    PRIMARY KEY CLUSTERED ([NCOM] ASC),
    FOREIGN KEY ([NCLI]) REFERENCES [dbo].[CLIENT] ([NCLI])
);
CREATE TABLE [dbo].[PRODUIT] (
    [NPRO]    CHAR (4)     NOT NULL,
    [LIBELLE] VARCHAR (50) NOT NULL,
    [PRIX]    INT          NOT NULL,
    [QSTOCK]  INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([NPRO] ASC)
);
CREATE TABLE [dbo].[DETAIL] (
    [NCOM]   CHAR (4) NOT NULL,
    [NPRO]   CHAR (4) NOT NULL,
    [QSTOCK] INT      NOT NULL,
    PRIMARY KEY CLUSTERED ([NCOM] ASC, [NPRO] ASC),
    FOREIGN KEY ([NCOM]) REFERENCES [dbo].[COMMANDE] ([NCOM]),
    FOREIGN KEY ([NPRO]) REFERENCES [dbo].[PRODUIT] ([NPRO])
);
